### ISSUE TITLE
When will the code and data be uploaded?

### ISSUE THREAD

**Issue by 128jcw** [bflashcp3f/schema-to-json#1]

**Comment by bflashcp3f** [comment]
Hi,

Thanks for your interest! We don't have a concrete plan yet, but hopefully code and data will be released by the end of August.

**Comment by 128jcw** [comment]
> Hi,
> 
> Thanks for your interest! We don't have a concrete plan yet, but hopefully code and data will be released by the end of August.

Thank you for answering!
