### ISSUE TITLE
When to release code

### ISSUE THREAD

**Issue by midannii** [bflashcp3f/schema-to-json#2]
Hi. 

I was so impressed with your paper and I might be very grateful if you release the code.
As I know, the code was scheduled to be released last month (https://github.com/bflashcp3f/schema-to-json/issues/1) 
Is there any new plan for this?

**Comment by bflashcp3f** [comment]
Hi Midan,

Thanks for your interest. Due to some personal matters, there has been a delay in the release of the code and data. We are now aiming to release them by October 6th at the latest. Appreciate your understanding!

Best,
-Fan

**Comment by bflashcp3f** [comment]
Hi Midan, 

The prompting code and data have been uploaded. Please let me know if you have any questions.
