### ISSUE TITLE
AttributeError: 'MLTables' object has no attribute 'get_prompt_list'

### ISSUE THREAD

**Issue by satvik-27199** [bflashcp3f/schema-to-json#5]
Thank you for the amazing work. To compare the performance difference between the "cell_by_cell" and "row_by_row" prompting methods, I have been trying to reproduce the experiments on MLTables using the "one_by_one" prompt setting. While the error recovery works well, I am encountering some issues with the "one_by_one" setting. Specifically, the 'get_prompt_list' attribute is not defined in MLTables as it is in the SWDE task.

sys.argv = [
    'yourr_script.py',
    '--run_type', 'prompt',
    '--template', 'template_xxxx',
    '--api_source', 'openai',
    '--backend', 'gpt-4',
    '--task', 'mltables',
    '--prompt_setting', 'one_by_one',
    '--task_start_index', '0',  # Convert integers to strings
    '--task_end_index', '10',   # Convert integers to strings
    '--max_tokens', '2048',     # Convert integers to strings
    '--stop', '\n\n',
    '--data_split', 'reduced_10',
    '--num_passes', '5']

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-36-f9c1cc902505>](https://localhost:8080/#) in <cell line: 2>()
     22     elif args.prompt_setting == 'one_by_one':
     23         if not args.api_source == 'open_source':
---> 24             prompt_one_by_one(args, task)
     25         else:
     26             prompt_one_by_one(args, task, open_source=True)

[<ipython-input-23-7c218150433e>](https://localhost:8080/#) in prompt_one_by_one(args, task, open_source)
    398 
    399     #prompt_list = task.get_input_list()
--> 400     prompt_list = task.get_prompt_list(encoding, max_length)
    401     print(prompt_list)
    402 

AttributeError: 'MLTables' object has no attribute 'get_prompt_list'

**Comment by bflashcp3f** [comment]
The code for cell-by-cell prompting has not been uploaded as it is not part of our main contribution. The current `one_by_one` setting is only for the SWDE dataset. If I have time, I will probably upload the code sometime next month.
